import React, { useState } from 'react';
import { motion } from 'motion/react';
import { ShieldCheck, Cpu, CheckCircle2, ChevronDown, HelpCircle, Lock, Sparkles, Layers, Calculator, Building2, Brain, AlertCircle } from 'lucide-react';

export const HowItWorksAndFAQ: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [activeFaqCategory, setActiveFaqCategory] = useState<
    'All' | 'ML & Eligibility' | 'Digital Twin' | 'Bank Marketplace' | 'AI & Recovery'
  >('All');

  const steps = [
    {
      num: '01',
      title: 'Authenticated Financial Profile',
      desc: 'Connect your financial profile securely. LifeLoan organizes your income, monthly expenses, existing debt, and credit score into a unified financial model.',
      icon: Cpu,
    },
    {
      num: '02',
      title: 'Trained ML Risk Assessment',
      desc: 'Our trained machine learning model evaluates default probability, debt-to-income (DTI) metrics, and repayment capability to recommend sustainable borrowing limits.',
      icon: Sparkles,
    },
    {
      num: '03',
      title: 'Digital Twin & Bank Intelligence',
      desc: 'Simulate scenario outcomes with your Financial Digital Twin, compare competitive rates across Indian lenders, and build custom recovery roadmaps.',
      icon: ShieldCheck,
    },
  ];

  const faqs = [
    {
      category: 'ML & Eligibility',
      q: 'What is LifeLoan?',
      a: 'LifeLoan is an AI-powered financial intelligence platform designed for Indian borrowers. It provides real-time machine learning credit risk evaluations, loan eligibility predictions, Financial Digital Twin simulations, bank marketplace rate comparisons, and interactive AI advisory.',
    },
    {
      category: 'ML & Eligibility',
      q: 'How does loan eligibility prediction work?',
      a: 'LifeLoan evaluates your application using a trained machine learning classification and regression pipeline. It processes key financial metrics including your Gross Annual Income, Debt-to-Income (DTI) ratio, credit score, monthly liabilities, and loan tenure to calculate your risk tier and sustainable borrowing capacity.',
    },
    {
      category: 'ML & Eligibility',
      q: 'What does default probability mean?',
      a: 'Default probability is an algorithmic percentage estimate generated by the ML model. It indicates the statistical likelihood of repayment distress based on your financial ratios. A lower default probability (e.g. <30%) reflects a healthier financial cushion and lower borrowing risk.',
    },
    {
      category: 'ML & Eligibility',
      q: 'What is the AI Recommended Loan Amount vs Requested Loan Amount?',
      a: 'The Requested Loan Amount is what you specify in your application (e.g. ₹5,00,000). The AI Recommended Loan Amount is what the machine learning model calculates as a safe, sustainable borrowing threshold that avoids over-leveraging your monthly cashflow. It is an algorithmic guideline, not a guaranteed bank offer.',
    },
    {
      category: 'ML & Eligibility',
      q: 'Is an ML approval a guaranteed bank approval?',
      a: 'No. An ML approval indicates that your current financial profile meets LifeLoan’s modeled risk parameters. Formal loan sanctions and fund disbursements are subject to official application and verification by registered commercial banks or NBFCs.',
    },
    {
      category: 'Digital Twin',
      q: 'How does the Financial Digital Twin work?',
      a: 'Your Financial Digital Twin is an interactive simulation sandbox. It takes your real baseline financial profile and allows you to adjust hypothetical loan amounts (₹50K–₹50L), interest rates, and income changes. The real-time ML engine instantly projects the resulting shift in default probability and monthly cashflow buffer.',
    },
    {
      category: 'Bank Marketplace',
      q: 'How does Bank Comparison work?',
      a: 'The Bank Comparison Marketplace aggregates current indicative interest rates, estimated processing fees, and projected monthly EMIs across premier Indian lenders including SBI, HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, and Bajaj Finserv to help you identify cost-effective borrowing options.',
    },
    {
      category: 'AI & Recovery',
      q: 'What does the Financial Recovery Planner do?',
      a: 'The Recovery Planner generates a prioritized 30/60/90-day actionable roadmap if your application shows higher risk or if you want to optimize your credit health. It provides concrete recommendations for lowering debt obligations, increasing liquid emergency buffers, and boosting credit scores.',
    },
    {
      category: 'ML & Eligibility',
      q: 'How is EMI calculated in LifeLoan?',
      a: 'EMIs are computed using the standard reducing-balance amortization formula: [P × r × (1 + r)^n] / [(1 + r)^n - 1], where P is Principal, r is the monthly interest rate, and n is the tenure in months. The EMI Calculator also provides full month-by-month principal and interest breakdowns.',
    },
    {
      category: 'AI & Recovery',
      q: 'What information does the AI Advisor use?',
      a: 'The AI Financial Advisor is securely grounded in your authentic database profile—including your annual income, existing debt liabilities, credit score, active loans, and latest SHAP/XAI risk factors. It answers questions about why specific decisions occurred without guessing or hallucinating facts.',
    },
  ];

  const filteredFaqs =
    activeFaqCategory === 'All'
      ? faqs
      : faqs.filter((f) => f.category === activeFaqCategory);

  return (
    <section id="how-it-works" className="relative py-20 lg:py-28 bg-[#0e1511]">
      <div className="mx-auto max-w-7xl px-6 lg:px-10">
        {/* HOW IT WORKS SECTION */}
        <div className="mb-20">
          <div className="text-center mb-14">
            <div className="inline-flex items-center space-x-2 text-xs font-bold tracking-[0.2em] text-[#4edea3] uppercase mb-3">
              <Layers className="h-4 w-4" />
              <span>THE ARCHITECTURE</span>
            </div>
            <h2 className="font-serif text-3xl font-bold tracking-tight text-[#dde4dd] sm:text-4xl lg:text-5xl">
              How LifeLoan Intelligence Works.
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {steps.map((step, index) => {
              const IconComp = step.icon;
              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.15 }}
                  className="glass-panel rounded-2xl p-6 lg:p-8 relative border border-[#242c27] glass-panel-hover"
                >
                  <div className="flex items-center justify-between mb-6">
                    <span className="font-mono text-3xl font-bold text-[#4edea3]/40">
                      {step.num}
                    </span>
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#10b981]/15 text-[#4edea3] border border-[#10b981]/30">
                      <IconComp className="h-5 w-5" />
                    </div>
                  </div>

                  <h3 className="font-serif text-xl font-bold text-[#dde4dd] mb-3">
                    {step.title}
                  </h3>

                  <p className="text-xs leading-relaxed text-[#bbcabf]">
                    {step.desc}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* FAQ SECTION */}
        <div id="faq" className="pt-10 border-t border-[#242c27]">
          <div className="text-center mb-12">
            <div className="inline-flex items-center space-x-2 text-xs font-bold tracking-[0.2em] text-[#4edea3] uppercase mb-3">
              <HelpCircle className="h-4 w-4" />
              <span>DOCUMENTATION & FREQUENTLY ASKED QUESTIONS</span>
            </div>
            <h2 className="font-serif text-3xl font-bold tracking-tight text-[#dde4dd] sm:text-4xl">
              Everything You Need to Know.
            </h2>
            <p className="mt-2 text-xs text-[#819087] max-w-xl mx-auto">
              Clear, transparent explanations of LifeLoan’s machine learning assessments, financial digital twin, and bank intelligence.
            </p>

            {/* Category Filters */}
            <div className="mt-6 flex flex-wrap justify-center gap-2">
              {(
                [
                  'All',
                  'ML & Eligibility',
                  'Digital Twin',
                  'Bank Marketplace',
                  'AI & Recovery',
                ] as const
              ).map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveFaqCategory(cat)}
                  className={`rounded-full px-4 py-1.5 text-xs font-semibold transition-all ${
                    activeFaqCategory === cat
                      ? 'bg-[#10b981] text-[#003824] shadow-md shadow-[#10b981]/20'
                      : 'border border-[#2f3632] bg-[#161d19] text-[#bbcabf] hover:text-[#dde4dd]'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Accordion List */}
          <div className="mx-auto max-w-3xl space-y-4">
            {filteredFaqs.map((faq, index) => {
              const isOpen = openFaq === index;
              return (
                <div
                  key={index}
                  className="rounded-2xl glass-panel border border-[#242c27] overflow-hidden transition-colors"
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : index)}
                    className="w-full flex items-center justify-between p-5 text-left text-sm font-semibold text-[#dde4dd] hover:text-[#4edea3] transition-colors"
                  >
                    <span>{faq.q}</span>
                    <ChevronDown
                      className={`h-4 w-4 shrink-0 text-[#4edea3] transition-transform duration-200 ml-3 ${
                        isOpen ? 'rotate-180' : ''
                      }`}
                    />
                  </button>

                  {isOpen && (
                    <div className="px-5 pb-5 pt-1 border-t border-[#1a211d] text-xs leading-relaxed text-[#bbcabf]">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
};
