import React from 'react';
import { ShieldCheck, ArrowLeft, FileText, AlertCircle, Scale, CheckCircle2, Building2, Cpu, Sparkles } from 'lucide-react';

interface TermsAndConditionsProps {
  onBack: () => void;
}

export const TermsAndConditions: React.FC<TermsAndConditionsProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-[#0e1511] text-[#dde4dd] py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#242c27] pb-6">
          <button
            type="button"
            onClick={onBack}
            className="flex items-center gap-2 text-xs font-semibold text-[#819087] hover:text-[#4edea3] transition w-fit"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Back to LifeLoan</span>
          </button>

          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-[#10b981] to-[#047857]">
              <ShieldCheck className="h-5 w-5 text-[#003824]" />
            </div>
            <span className="font-serif text-xl font-bold">
              Life<span className="text-[#4edea3]">Loan</span>
            </span>
          </div>
        </div>

        {/* Title */}
        <div className="space-y-2">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#10b981]/10 border border-[#4edea3]/30 text-[11px] font-bold text-[#4edea3] uppercase tracking-wider">
            <Scale className="h-3.5 w-3.5" />
            <span>Platform Terms & Disclaimers</span>
          </div>
          <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-[#dde4dd]">
            Terms & Conditions
          </h1>
          <p className="text-xs sm:text-sm text-[#819087]">
            Last updated: September 2026 • Governing use of the LifeLoan intelligence platform
          </p>
        </div>

        {/* Content Sections */}
        <div className="space-y-6">

          {/* 1. Purpose of LifeLoan */}
          <section className="rounded-2xl border border-[#242c27] bg-[#161d19] p-6 sm:p-8 space-y-3">
            <div className="flex items-center gap-2.5 text-[#4edea3] font-bold text-sm">
              <FileText className="h-4 w-4" />
              <h2>1. Educational & Decision-Support Scope</h2>
            </div>
            <p className="text-xs leading-relaxed text-[#bbcabf]">
              LifeLoan provides financial intelligence, machine learning-driven credit risk evaluations, borrowing capacity forecasting, and repayment simulations. The platform is designed solely as an educational, analytical, and decision-support tool for borrowers in India. LifeLoan is not a direct non-banking financial company (NBFC) or a commercial bank.
            </p>
          </section>

          {/* 2. Machine Learning Estimates */}
          <section className="rounded-2xl border border-[#242c27] bg-[#161d19] p-6 sm:p-8 space-y-4">
            <div className="flex items-center gap-2.5 text-[#4edea3] font-bold text-sm">
              <Cpu className="h-4 w-4" />
              <h2>2. ML Predictions are Estimates, Not Loan Sanctions</h2>
            </div>
            <div className="space-y-3 text-xs text-[#bbcabf]">
              <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 flex items-start gap-3">
                <AlertCircle className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
                <p className="text-[11px] leading-relaxed text-amber-200/90">
                  <strong>Important Notice:</strong> A positive ML assessment (e.g. "Approved") or a low predicted default probability indicates that your financial profile meets LifeLoan's modeled risk criteria. It is <em>not</em> a formal bank sanction letter, guarantee of disbursal, or binding lender commitment.
                </p>
              </div>
              <ul className="space-y-2 list-disc list-inside text-[#86948a] text-[11px] leading-relaxed">
                <li><strong>AI Recommended Amount:</strong> The recommended loan amount generated by the model reflects an algorithmically sustainable borrowing ceiling based on your reported DTI and income, not an approved bank credit line.</li>
                <li><strong>SHAP / XAI Factors:</strong> Feature importance attributions illustrate how specific parameters influenced the model's prediction and do not constitute individual pass/fail underwriting criteria.</li>
              </ul>
            </div>
          </section>

          {/* 3. Bank Comparison Marketplace */}
          <section className="rounded-2xl border border-[#242c27] bg-[#161d19] p-6 sm:p-8 space-y-3">
            <div className="flex items-center gap-2.5 text-[#4edea3] font-bold text-sm">
              <Building2 className="h-4 w-4" />
              <h2>3. Bank & Lender Comparison Information</h2>
            </div>
            <p className="text-xs leading-relaxed text-[#bbcabf]">
              The Bank Comparison Marketplace aggregates indicative interest rate benchmarks, estimated processing fees, and illustrative EMI figures for institutions including State Bank of India, HDFC Bank, ICICI Bank, Axis Bank, Kotak Mahindra Bank, and Bajaj Finserv. Rates and eligibility terms are subject to change by the respective financial institutions and depend on formal underwriting, KYC verification, and documentation.
            </p>
          </section>

          {/* 4. Digital Twin & Scenario Simulations */}
          <section className="rounded-2xl border border-[#242c27] bg-[#161d19] p-6 sm:p-8 space-y-3">
            <div className="flex items-center gap-2.5 text-[#4edea3] font-bold text-sm">
              <Sparkles className="h-4 w-4" />
              <h2>4. Digital Twin Simulations & AI Advisory</h2>
            </div>
            <p className="text-xs leading-relaxed text-[#bbcabf]">
              Simulations executed in the Financial Digital Twin, EMI Calculator, and 30/60/90-Day Recovery Planner represent hypothetical financial modeling based on user-supplied variables. Responses from the AI Financial Advisor are generated dynamically for informational guidance and do not constitute certified legal, tax, or professional investment advice.
            </p>
          </section>

          {/* 5. User Responsibilities */}
          <section className="rounded-2xl border border-[#242c27] bg-[#161d19] p-6 sm:p-8 space-y-3">
            <div className="flex items-center gap-2.5 text-[#4edea3] font-bold text-sm">
              <CheckCircle2 className="h-4 w-4" />
              <h2>5. Accuracy of User Information</h2>
            </div>
            <p className="text-xs leading-relaxed text-[#bbcabf]">
              You agree to provide accurate, truthful financial profile metrics (income, expenses, debt liabilities, and credit score) to receive meaningful risk insights. LifeLoan is not liable for inaccurate predictions resulting from erroneous user input.
            </p>
          </section>

        </div>

        {/* Footer CTA */}
        <div className="text-center pt-4 pb-8">
          <button
            type="button"
            onClick={onBack}
            className="rounded-xl bg-[#10b981] px-8 py-3 text-xs font-bold text-[#003824] hover:bg-[#4edea3] transition shadow-lg shadow-[#10b981]/20"
          >
            Return to Dashboard
          </button>
        </div>

      </div>
    </div>
  );
};

export default TermsAndConditions;
